Openblt considerations of artifacts
mck1117/wideband pull request #213
Opened 2023-02-28 01:05 UTC by rusefillc

#212 and more better artifacts for github action

2023-03-06 09:34 UTC, mck1117 commented
![image](https://user-images.githubusercontent.com/568254/223071588-9ed45cae-7226-46ea-b903-8da268387b11.png)

2023-03-06 09:34 UTC, mck1117 requested changes
![image](https://user-images.githubusercontent.com/568254/223071678-5161f0f9-ca01-46d7-ade4-c2fba97232c9.png)

2023-03-06 10:09 UTC, rusefillc commented on .github/workflows/build-firmware.yaml
> +          path: ./firmware/c/${{matrix.build-target}}/wideband.*
the typo is here

2023-03-06 10:39 UTC, rusefillc commented
typo in f1 script fixed, f0 script is now a bit more consistent with f1

2023-03-07 05:05 UTC, mck1117 commented
If this overlaps with now-merged #214, I'm happy to modify the F0 script to place output files as I theoretically maintain that board..

2023-03-07 05:14 UTC, rusefillc commented
@mck1117 you mean https://github.com/mck1117/wideband/pull/217?

2023-03-07 05:15 UTC, mck1117 commented
oops, 43def3f98257850f7820503f0984cda0e3c078d0 implemented f0 in master

2023-03-07 05:25 UTC, rusefillc commented
@mck1117 only F1 progress now here

2023-03-07 05:26 UTC, merged